sudo: required
language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
jobs:
  include:
    - stage: build
      script: 'ng build'
    - stage: prod
      script: 'ng build --prod'
    - stage: test
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - 'ng test --browsers PhantomJS --watch=false'
        - 'ng e2e'
stages:
  - build
  - prod
  - test
