sudo: required
language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
jobs:
  include:
    - stage: build
      script: 'ng build'
    - stage: prod
      script: 'ng build --prod'
    - stage: test
      script:
        - 'ng test --browsers PhantomJS --watch=false'
        - 'ng e2e'
stages:
  - build
  - prod
  - test
